"""Generate docs/moneybird_api_scopes.json from the official Moneybird OpenAPI spec.

The OAuth scopes this server requests must be justified per endpoint, and the
only authoritative statement of "which scope does this endpoint need" is the
``### Required scope(s)`` line in each operation's description on
developer.moneybird.com — mirrored verbatim in the published spec.

The ``security: bearerAuth: [...]`` array is **not** sufficient on its own: it
carries the same flat list whether the scopes are all required together
(``documents`` *and* ``sales_invoices`` for the profit-and-loss report) or any
one suffices (``Any of:`` for contacts, ledger accounts and tax rates). Only the
description text distinguishes the two, so that is what is parsed here.

Usage (network fetch is manual and deliberate; CI never has network):

    curl -sSLo openapi.yml \\
      https://raw.githubusercontent.com/moneybird/openapi/refs/heads/main/openapi.yml
    python scripts/render_api_scopes.py openapi.yml
    python scripts/render_api_scopes.py openapi.yml --check   # CI-style diff check

Requires PyYAML, which is a generator-only dependency and is deliberately not a
runtime or test dependency of the package.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "moneybird_api_scopes.json"
SOURCE_URL = (
    "https://raw.githubusercontent.com/moneybird/openapi/refs/heads/main/openapi.yml"
)

# The scope text ends at a blank line, at the next Markdown heading, or at the
# end of the description. The heading terminator matters: without it a section
# that runs straight into the next `###` with no blank line between them keeps
# matching, and any scope name mentioned in backticks further down (a response
# field, a cross-reference) is silently read as an extra required scope.
_SCOPE_HEADING = re.compile(
    r"### Required scope\(s\)\s*(.+?)(?:\n\s*\n|\n\s*#|$)", re.S
)
_SCOPE_NAME = re.compile(r"`([a-z_]+)`")

# Wordings that mean "one of these suffices". Getting this wrong is not
# symmetric: reading an "any" line as "all" merely overstates the request, but
# reading an "all" line as "any" would let the minimality test bless a scope set
# that cannot actually call the endpoint. Both directions are pinned by tests.
_ANY_OF_PREFIXES = ("any of", "any one of", "one of")


def normalize_path(path: str) -> str:
    """Match the convention in tests/test_client_spec_conformance.py."""
    path = path.replace("/{administration_id}", "").replace("{format}", "")
    return re.sub(r"\{[^}]+\}", "*", path).removesuffix(".json")


def parse_requirement(description: str) -> tuple[str, list[str]]:
    """('all' | 'any' | 'none', scopes) from an operation description."""
    match = _SCOPE_HEADING.search(description or "")
    if not match:
        return "none", []
    text = " ".join(match.group(1).split())
    scopes = _SCOPE_NAME.findall(text)
    if not scopes:
        return "none", []
    # "Any of: `estimates`, `sales_invoices`, ..." vs "`documents` and `sales_invoices`".
    mode = "any" if text.lower().startswith(_ANY_OF_PREFIXES) else "all"
    return mode, scopes


def build(spec: dict[str, Any]) -> dict[str, Any]:
    operations: dict[str, dict[str, Any]] = {}
    conflicts: list[str] = []
    for path, item in spec.get("paths", {}).items():
        normalized = normalize_path(path)
        for method, operation in item.items():
            if not isinstance(operation, dict) or "responses" not in operation:
                continue
            mode, scopes = parse_requirement(operation.get("description", ""))
            key = f"{method.upper()} {normalized}"
            record = {"mode": mode, "scopes": sorted(set(scopes))}
            existing = operations.get(key)
            if existing is not None and existing != record:
                # Collapsing {id} to * must never merge operations with different
                # requirements; that would silently understate what is needed.
                conflicts.append(f"{key}: {existing} != {record}")
            operations[key] = record
    if conflicts:
        raise SystemExit(
            "Normalised paths collide with differing scope requirements:\n  "
            + "\n  ".join(conflicts)
        )
    return {
        "info": {
            "version": spec.get("info", {}).get("version"),
            "retrieved": date.today().isoformat(),
            "source": SOURCE_URL,
            "note": (
                "Generated by scripts/render_api_scopes.py. 'mode' is 'all' when "
                "every listed scope is required together, 'any' when one suffices, "
                "'none' when the endpoint documents no scope requirement."
            ),
        },
        "operations": dict(sorted(operations.items())),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path, help="Path to a downloaded openapi.yml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the checked-in file differs (ignoring the timestamp).",
    )
    args = parser.parse_args(argv)

    try:
        import yaml
    except ImportError:
        parser.error("PyYAML is required to regenerate this file: pip install pyyaml")

    generated = build(yaml.safe_load(args.spec.read_text(encoding="utf-8")))
    rendered = json.dumps(generated, indent=1, sort_keys=False) + "\n"

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run without --check.")
            return 1
        current = json.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
        if current["operations"] != generated["operations"]:
            print(f"{OUTPUT_PATH} is out of date; rerun without --check.")
            return 1
        print(f"{OUTPUT_PATH} matches the spec.")
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {OUTPUT_PATH} "
        f"({len(generated['operations'])} operations, spec {generated['info']['version']})."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
